name: ${pluginName}
version: ${version}
main: com.chizstudio.misilelaboratory.DoxaPlugin
api-version: 1.18
libraries:
  - io.github.monun:kommand:2.7.0
  - io.github.monun:heartbeat-coroutines:0.0.3